"""empty message

Revision ID: 18294c5c02e9
Revises: 5dd0b4e5e3c6
Create Date: 2021-04-28 02:48:14.027519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18294c5c02e9'
down_revision = '5dd0b4e5e3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('nombre', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'nombre')
    # ### end Alembic commands ###
